import { auth, db } from "./firebase.js";
import { createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, onAuthStateChanged, updateProfile, sendPasswordResetEmail } from "https://www.gstatic.com/firebasejs/12.6.0/firebase-auth.js";
import { doc,setDoc,getDoc,collection,addDoc,query,where,getDocs,serverTimestamp } from "https://www.gstatic.com/firebasejs/12.6.0/firebase-firestore.js";
const $=id=>document.getElementById(id),views=["authView","waitingView","portalView"];function show(id){views.forEach(v=>$(v).hidden=v!==id)}function msg(t){$("authMessage").textContent=t||""}
$("loginTab").onclick=()=>{$("loginForm").hidden=false;$("registerForm").hidden=true;$("loginTab").classList.add("active");$("registerTab").classList.remove("active");msg("")};
$("registerTab").onclick=()=>{$("loginForm").hidden=true;$("registerForm").hidden=false;$("registerTab").classList.add("active");$("loginTab").classList.remove("active");msg("")};
$("forgotPassword").onclick=async()=>{const email=$("loginEmail").value.trim();if(!email)return msg("Skriv inn e-postadressen din først.");msg("Sender e-post…");try{await sendPasswordResetEmail(auth,email);msg("Hvis e-postadressen er registrert, er det sendt en lenke for å lage nytt passord.")}catch(e){msg("Kunne ikke sende e-post akkurat nå. Prøv igjen.")}};
$("loginForm").onsubmit=async e=>{e.preventDefault();msg("Logger inn…");try{await signInWithEmailAndPassword(auth,$("loginEmail").value.trim(),$("loginPassword").value)}catch(e){msg("Kunne ikke logge inn. Sjekk e-post og passord.")}};
$("registerForm").onsubmit=async e=>{e.preventDefault();const name=$("registerName").value.trim(),password=$("registerPassword").value,confirm=$("registerPasswordConfirm").value;if(name.length<3)return msg("Skriv inn fullt navn.");if(password!==confirm)return msg("Passordene er ikke like.");msg("Oppretter konto…");try{const c=await createUserWithEmailAndPassword(auth,$("registerEmail").value.trim(),password);await updateProfile(c.user,{displayName:name});await setDoc(doc(db,"playerAccounts",c.user.uid),{name,email:c.user.email,approved:false,playerId:null,createdAt:serverTimestamp()})}catch(e){msg(e.code==="auth/email-already-in-use"?"Denne e-postadressen er allerede registrert. Prøv å logge inn.":"Kunne ikke opprette konto. Kontroller opplysningene og prøv igjen.")}};
document.querySelectorAll(".logout").forEach(b=>b.onclick=()=>signOut(auth));$("developmentBtn").onclick=()=>{$("developmentPanel").hidden=false;$("developmentPanel").scrollIntoView({behavior:"smooth"})};$("closeDevelopment").onclick=()=>$("developmentPanel").hidden=true;
$("matchesLink").onclick=e=>{e.preventDefault();alert("Kampoversikten kobles inn når spillertrygge kampdata er kontrollert.")};$("videoLink").onclick=e=>{e.preventDefault();alert("Kamprommet kobles inn etter kontroll av eksisterende innlogging.")};
let account=null,currentUser=null;
$("activatePortal").onclick=async()=>{if(!currentUser)return;const name=$("activationName").value.trim()||currentUser.displayName||"";if(name.length<3)return msg("Skriv inn fullt navn.");$("activatePortal").disabled=true;try{await setDoc(doc(db,"playerAccounts",currentUser.uid),{name,email:currentUser.email,approved:false,playerId:null,createdAt:serverTimestamp()});$("waitingName").textContent=name;$("legacyActivation").hidden=true;show("waitingView")}catch(e){msg("Kunne ikke aktivere Spillerportalen. Prøv igjen.")}finally{$("activatePortal").disabled=false}};
async function loadRequest(){if(!account?.playerId)return;const q=query(collection(db,"developmentRequests"),where("uid","==",currentUser.uid),where("status","==","open"));const s=await getDocs(q),d=s.docs[0];$("requestArea").hidden=!!d;$("activeRequest").hidden=!d;if(d){const x=d.data();$("activeRequestText").textContent=x.message?"Tema: "+x.message:"Du har bedt om en generell tilbakemelding."}}
async function loadMessages(){if(!account?.playerId)return;try{const q=query(collection(db,"developmentMessages"),where("playerId","==",account.playerId));const s=await getDocs(q);const docs=s.docs.sort((a,b)=>(b.data().createdAt?.seconds||0)-(a.data().createdAt?.seconds||0));$("messages").innerHTML=docs.length===0?'<p class="hint">Ingen meldinger ennå.</p>':docs.map(d=>{const x=d.data();return '<div class="msg"><strong>'+(x.senderRole==="coach"?"Trener":"Deg")+'</strong><p>'+escapeHtml(x.text||"")+'</p></div>'}).join("")}catch(e){$("messages").innerHTML='<p class="hint">Ingen meldinger ennå.</p>'}}
$("requestBtn").onclick=async()=>{if(!account?.playerId)return;const t=$("requestText").value.trim();$("requestBtn").disabled=true;try{await addDoc(collection(db,"developmentRequests"),{uid:currentUser.uid,playerId:account.playerId,message:t,status:"open",createdAt:serverTimestamp(),resolvedAt:null});await loadRequest()}finally{$("requestBtn").disabled=false}};
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
onAuthStateChanged(auth,async user=>{currentUser=user;if(!user){account=null;show("authView");return}const s=await getDoc(doc(db,"playerAccounts",user.uid));if(!s.exists()){const legacy=await getDoc(doc(db,"users",user.uid));if(legacy.exists()&&["coach","assistantCoach"].includes(legacy.data().role)){await signOut(auth);show("authView");$("loginForm").hidden=false;$("registerForm").hidden=true;$("legacyActivation").hidden=true;msg("Denne kontoen er en trenerkonto og kan ikke aktiveres som spillerkonto.");return}account=null;show("authView");$("loginForm").hidden=false;$("registerForm").hidden=true;$("loginTab").classList.add("active");$("registerTab").classList.remove("active");$("legacyActivation").hidden=false;$("activationName").value=user.displayName||"";msg("Du er logget inn. Aktiver Spillerportalen for å fortsette.");return}$("legacyActivation").hidden=true;account=s.data();if(!account.approved||!account.playerId){$("waitingName").textContent=account.name||user.displayName||"";show("waitingView");return}$("hello").textContent="Hei, "+(account.name||"spiller").split(" ")[0]+"!";show("portalView");await Promise.all([loadRequest(),loadMessages()])});