import { auth, db, functions } from "./firebase.js";
import { createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, onAuthStateChanged, updateProfile, sendPasswordResetEmail } from "https://www.gstatic.com/firebasejs/12.6.0/firebase-auth.js";
import { doc,setDoc,getDoc,collection,addDoc,query,where,getDocs,serverTimestamp,onSnapshot,deleteDoc } from "https://www.gstatic.com/firebasejs/12.6.0/firebase-firestore.js";
import { httpsCallable } from "https://www.gstatic.com/firebasejs/12.6.0/firebase-functions.js";
const $=id=>document.getElementById(id),views=["guardianInviteView","authView","waitingView","parentWaitingView","parentView","portalView"];function show(id){views.forEach(v=>$(v).hidden=v!==id)}function msg(t){$("authMessage").textContent=t||""}
$("loginTab").onclick=()=>{$("loginForm").hidden=false;$("registerForm").hidden=true;$("loginTab").classList.add("active");$("registerTab").classList.remove("active");msg("")};
const passwordInput=$("registerPassword"),confirmStep=$("passwordConfirmStep"),confirmInput=$("registerPasswordConfirm");
function showPasswordConfirm(){if(passwordInput.value.length<6)return;confirmStep.hidden=false;$("registerPasswordLabel").hidden=true;confirmInput.required=true;confirmInput.focus()}
$("passwordNext").onclick=()=>{if(passwordInput.value.length<6){msg("Passordet må ha minst 6 tegn.");passwordInput.focus();return}showPasswordConfirm()};
passwordInput.addEventListener("keydown",e=>{if(e.key==="Enter"&&passwordInput.value.length>=6){e.preventDefault();showPasswordConfirm()}});
$("changePassword").onclick=()=>{confirmStep.hidden=true;$("registerPasswordLabel").hidden=false;confirmInput.required=false;confirmInput.value="";passwordInput.focus()};
const inviteParams=new URLSearchParams(location.search),guardianInviteToken=inviteParams.get("guardianInvite");let guardianInviteData=null;
async function loadGuardianInvite(){if(!guardianInviteToken)return false;show("guardianInviteView");$("guardianInviteMessage").textContent="Kontrollerer invitasjonen…";try{const fn=httpsCallable(functions,"getGuardianInvite"),res=await fn({token:guardianInviteToken});guardianInviteData=res.data;$("guardianInviteEmail").value=guardianInviteData.email;$("guardianInviteName").textContent="Hei, "+(guardianInviteData.guardianName||"foresatt");$("guardianInvitePlayer").textContent="Invitert som foresatt til "+(guardianInviteData.playerName||"spilleren");$("guardianInviteMessage").textContent="";return true}catch(e){console.error(e);$("guardianInviteMessage").textContent="Invitasjonen er ugyldig, brukt eller utløpt.";return true}}
$("guardianInviteCreate").onclick=async()=>{if(!guardianInviteData)return;const p=$("guardianInvitePassword").value,p2=$("guardianInvitePassword2").value,m=$("guardianInviteMessage"),btn=$("guardianInviteCreate");if(p.length<6)return m.textContent="Passordet må ha minst 6 tegn.";if(p!==p2)return m.textContent="Passordene er ikke like.";btn.disabled=true;btn.textContent="Oppretter…";try{const c=await createUserWithEmailAndPassword(auth,guardianInviteData.email,p);await updateProfile(c.user,{displayName:guardianInviteData.guardianName||"Foresatt"});const claim=httpsCallable(functions,"claimGuardianInvite");await claim({token:guardianInviteToken});history.replaceState({},document.title,location.pathname);m.textContent="Kontoen er opprettet. Åpner foresattportalen…";location.reload();return}catch(e){console.error(e);if(e.code==="auth/email-already-in-use"){$("guardianExistingLogin").hidden=false;$("guardianInviteCreate").hidden=true;m.textContent="Kontoen finnes allerede. Logg inn under for å bruke invitasjonen."}else{m.textContent="Kunne ikke opprette foresattkontoen."}}finally{btn.disabled=false;btn.textContent="Opprett foresattkonto"}};
loadGuardianInvite();
$("guardianExistingLoginBtn").onclick=async()=>{if(!guardianInviteData)return;const p=$("guardianExistingPassword").value,m=$("guardianInviteMessage"),btn=$("guardianExistingLoginBtn");if(!p)return m.textContent="Skriv inn passordet til den eksisterende kontoen.";btn.disabled=true;btn.textContent="Logger inn…";try{await signInWithEmailAndPassword(auth,guardianInviteData.email,p);m.textContent="Innlogget. Kobler invitasjonen…"}catch(e){console.error(e);m.textContent="Kunne ikke logge inn. Sjekk passordet eller bruk «Glemt passord?»."}finally{btn.disabled=false;btn.textContent="Logg inn og fortsett"}};
$("guardianExistingForgot").onclick=async()=>{if(!guardianInviteData)return;const m=$("guardianInviteMessage");try{await sendPasswordResetEmail(auth,guardianInviteData.email);m.textContent="Hvis kontoen kan tilbakestilles, er det sendt en e-post med lenke for nytt passord."}catch(e){console.error(e);m.textContent="Kunne ikke sende e-post akkurat nå."}};

$("registerTab").onclick=()=>{$("loginForm").hidden=true;$("registerForm").hidden=false;$("registerTab").classList.add("active");$("loginTab").classList.remove("active");msg("")};
$("forgotPassword").onclick=async()=>{const email=$("loginEmail").value.trim();if(!email)return msg("Skriv inn e-postadressen din først.");msg("Sender e-post…");try{await sendPasswordResetEmail(auth,email);msg("Hvis e-postadressen er registrert, er det sendt en lenke for å lage nytt passord.")}catch(e){msg("Kunne ikke sende e-post akkurat nå. Prøv igjen.")}};
$("loginForm").onsubmit=async e=>{e.preventDefault();msg("Logger inn…");try{await signInWithEmailAndPassword(auth,$("loginEmail").value.trim(),$("loginPassword").value)}catch(e){msg("Kunne ikke logge inn. Sjekk e-post og passord.")}};
$("registerForm").onsubmit=async e=>{e.preventDefault();const name=$("registerName").value.trim(),password=$("registerPassword").value,confirm=$("registerPasswordConfirm").value;if(name.length<3)return msg("Skriv inn fullt navn.");if(confirmStep.hidden){showPasswordConfirm();return msg("Gjenta passordet før kontoen opprettes.");}if(password!==confirm)return msg("Passordene er ikke like.");msg("Oppretter konto…");try{const c=await createUserWithEmailAndPassword(auth,$("registerEmail").value.trim(),password);await updateProfile(c.user,{displayName:name});await setDoc(doc(db,"playerAccounts",c.user.uid),{name,email:c.user.email,approved:false,playerId:null,createdAt:serverTimestamp()})}catch(e){msg(e.code==="auth/email-already-in-use"?"Denne e-postadressen er allerede registrert. Prøv å logge inn.":"Kunne ikke opprette konto. Kontroller opplysningene og prøv igjen.")}};
let guardianRequestUnsub=null;
function startGuardianRequestListener(){guardianRequestUnsub?.();if(!account?.playerId||!currentUser)return;const q=query(collection(db,"guardianRequests"),where("playerUid","==",currentUser.uid),where("playerId","==",account.playerId));guardianRequestUnsub=onSnapshot(q,s=>{const rows=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));$("myGuardians").innerHTML=rows.length?rows.map(r=>'<div class="guardianRequestRow"><div><strong>'+escapeHtml(r.guardianName||"Foresatt")+'</strong><span>'+escapeHtml(r.guardianEmail||"")+'</span></div><span class="guardianStatus '+escapeHtml(r.status||"pending")+'">'+(r.status==="approved"?"GODKJENT":r.status==="rejected"?"AVVIST":"VENTER PÅ TRENER")+'</span></div>').join(""):'<p class="hint">Du har ikke lagt til noen foresatte ennå.</p>'},e=>{console.error("guardian request listener",e);$("myGuardians").innerHTML='<p class="hint">Kunne ikke laste foresatte.</p>'})}
$("guardiansBtn").onclick=()=>{$("guardianPanel").hidden=false;$("guardianPanel").scrollIntoView({behavior:"smooth",block:"start"})};$("closeGuardians").onclick=()=>{$("guardianPanel").hidden=true;$("guardianRequestForm").hidden=true;$("openGuardianRequest").hidden=false};
$("openGuardianRequest").onclick=()=>{$("guardianRequestForm").hidden=false;$("openGuardianRequest").hidden=true;$("guardianRequestName").focus()};
$("cancelGuardianRequest").onclick=()=>{$("guardianRequestForm").hidden=true;$("openGuardianRequest").hidden=false};
$("sendGuardianRequest").onclick=async()=>{const name=$("guardianRequestName").value.trim(),email=$("guardianRequestEmail").value.trim().toLowerCase(),btn=$("sendGuardianRequest");if(name.length<3)return alert("Skriv inn navnet på foresatte.");if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email))return alert("Skriv inn en gyldig e-postadresse.");if(!confirm("Sende "+name+" ("+email+") til trener for godkjenning?"))return;btn.disabled=true;btn.textContent="Sender…";try{const existing=await getDocs(query(collection(db,"guardianRequests"),where("playerUid","==",currentUser.uid),where("guardianEmail","==",email)));if(existing.docs.some(d=>d.data().status!=="rejected"))return alert("Denne e-postadressen er allerede lagt til.");await addDoc(collection(db,"guardianRequests"),{playerUid:currentUser.uid,playerId:account.playerId,playerName:account.name||currentUser.displayName||"",guardianName:name,guardianEmail:email,status:"pending",createdAt:serverTimestamp()});$("guardianRequestName").value="";$("guardianRequestEmail").value="";$("guardianRequestForm").hidden=true;$("openGuardianRequest").hidden=false}catch(e){console.error(e);alert("Kunne ikke sende forespørselen. Firestore-reglene må tillate guardianRequests.")}finally{btn.disabled=false;btn.textContent="Send til trener"}};
$("openRequestForm").onclick=()=>{$("requestIntro").hidden=true;$("requestForm").hidden=false};$("cancelRequest").onclick=()=>{$("requestForm").hidden=true;$("requestIntro").hidden=false;$("requestText").value=""};document.querySelectorAll(".logout").forEach(b=>b.onclick=()=>signOut(auth));$("developmentBtn").onclick=()=>{$("developmentPanel").hidden=false;$("developmentPanel").scrollIntoView({behavior:"smooth"})};$("closeDevelopment").onclick=()=>$("developmentPanel").hidden=true;
let account=null,guardianAccount=null,currentUser=null,requestSubmitting=false,replySubmitting=false,unsubscribeRequests=null,unsubscribeMessages=null,allMessages=[],allRequests=[],showAllMessages=false,showArchived=false,activeRequestId=null,replyToMessageId=null;
$("activatePortal").onclick=async()=>{if(!currentUser)return;const name=$("activationName").value.trim()||currentUser.displayName||"";if(name.length<3)return msg("Skriv inn fullt navn.");$("activatePortal").disabled=true;try{await setDoc(doc(db,"playerAccounts",currentUser.uid),{name,email:currentUser.email,approved:false,playerId:null,createdAt:serverTimestamp()});$("waitingName").textContent=name;$("legacyActivation").hidden=true;show("waitingView")}catch(e){msg("Kunne ikke aktivere Spillerportalen. Prøv igjen.")}finally{$("activatePortal").disabled=false}};
function renderRequestDocs(docs){allRequests=docs.map(x=>({id:x.id,...x.data()}));const openRequests=allRequests.filter(x=>x.status==="open").sort((a,b)=>(b.reopenedAt?.seconds||b.createdAt?.seconds||0)-(a.reopenedAt?.seconds||a.createdAt?.seconds||0));const d=openRequests[0]||null;activeRequestId=d?.id||null;if(!d)clearReplyTarget();renderMessages();$("requestArea").hidden=!!d;$("activeRequest").hidden=!d;if(d){const coachStarted=d.startedBy==="coach";$("playerReplyArea").hidden=false;const box=$("activeRequest");box.querySelector(".activeStatusHead strong").textContent=coachStarted?"Trener har startet en samtale":"✓ Du har bedt om tilbakemelding";box.querySelector("small").textContent=coachStarted?"Samtalen står aktiv til den blir avsluttet.":"Forespørselen står aktiv til trener har fulgt den opp.";$("activeRequestText").textContent="Tema: "+(d.title||"Utviklingssamtale")}else{$("playerReplyArea").hidden=true;$("requestForm").hidden=true;$("requestIntro").hidden=false;$("requestBtn").disabled=false;$("requestBtn").textContent="Send forespørsel"}}
function startDevelopmentListeners(){if(!account?.playerId||!currentUser)return;unsubscribeRequests?.();unsubscribeMessages?.();const rq=query(collection(db,"developmentRequests"),where("uid","==",currentUser.uid),where("playerId","==",account.playerId));unsubscribeRequests=onSnapshot(rq,s=>renderRequestDocs(s.docs),e=>{console.error("request listener",e);$("requestArea").hidden=false;$("activeRequest").hidden=true});const mq=query(collection(db,"developmentMessages"),where("playerId","==",account.playerId));unsubscribeMessages=onSnapshot(mq,s=>{allMessages=s.docs.sort((a,b)=>(b.data().createdAt?.seconds||0)-(a.data().createdAt?.seconds||0));renderMessages()},e=>{console.error("message listener",e);$("messages").innerHTML='<p class="hint">Kunne ikke laste meldinger.</p>'})}
function renderMessages(){const active=activeRequestId?allRequests.find(r=>r.id===activeRequestId):null,archived=allRequests.filter(r=>r.status!=="open").sort((x,y)=>(y.createdAt?.seconds||0)-(x.createdAt?.seconds||0));const renderMsg=d=>{const x=d.data(),date=x.createdAt?.toDate?.(),parent=x.replyToMessageId?allMessages.find(m=>m.id===x.replyToMessageId):null,parentText=parent?.data()?.text||"",parentRole=parent?.data()?.senderRole;return '<div class="msg '+(x.senderRole==="coach"?"coachMessage":"playerMessage")+'">'+(parentText?'<div class="replyReference"><span>Svar på '+(parentRole==="coach"?"Trener":"deg")+'</span>'+escapeHtml(parentText)+'</div>':'')+'<div class="msgHead"><div><strong>'+(x.senderRole==="coach"?"Trener":"Deg")+'</strong>'+(date?'<small>'+date.toLocaleDateString("no-NO",{day:"numeric",month:"short",year:"numeric"})+'</small>':"")+'</div><div class="msgTools">'+(x.senderRole==="coach"&&active&&x.requestId===active.id?'<button class="replyMessage" data-id="'+d.id+'">Svar</button>':'')+'<button class="deleteMessage" data-id="'+d.id+'" title="Slett melding">Slett</button></div></div><p>'+escapeHtml(x.text||"")+'</p></div>'};const activeDocs=active?allMessages.filter(m=>m.data().requestId===active.id).sort((a,b)=>(a.data().createdAt?.seconds||0)-(b.data().createdAt?.seconds||0)):[];const starter=active&&active.startedBy==="coach"?'<div class="msg coachMessage"><div class="msgHead"><div><strong>Trener</strong></div></div><p>'+escapeHtml(active.message||"")+'</p></div>':"";$("messages").innerHTML=starter+(activeDocs.length?activeDocs.map(renderMsg).join(""):(active&&active.startedBy!=="coach"?'<p class="hint">Ingen svar i denne samtalen ennå.</p>':active?"":'<p class="hint">Ingen aktiv samtale.</p>'));$("messageToggle").hidden=true;$("archivedToggle").hidden=archived.length===0;$("archivedToggle").textContent="Arkiv ("+archived.length+")";$("archivedConversations").hidden=true;$("archivedConversations").innerHTML="";document.querySelectorAll(".deleteMessage").forEach(b=>b.onclick=deleteMessage);document.querySelectorAll(".replyMessage").forEach(b=>b.onclick=selectReplyTarget)}
function openPlayerArchive(){const archived=allRequests.filter(r=>r.status!=="open").sort((x,y)=>(y.createdAt?.seconds||0)-(x.createdAt?.seconds||0));clearReplyTarget();const archive=$("archivedConversations");archive.innerHTML='<div class="playerArchiveOverlay"><div class="playerArchiveModal"><div class="sectionTitle"><div><small>MIN UTVIKLING</small><h2>Tidligere samtaler</h2></div><button id="closePlayerArchive" class="ghost" type="button">Lukk</button></div>'+(archived.length?archived.map(r=>{const docs=allMessages.filter(m=>m.data().requestId===r.id).sort((x,y)=>(x.data().createdAt?.seconds||0)-(y.data().createdAt?.seconds||0)),created=r.createdAt?.toDate?.();return '<section class="playerArchiveConversation"><div class="playerArchiveHead"><div><strong>'+escapeHtml(r.title||"Utviklingssamtale")+'</strong><small>'+(created?created.toLocaleDateString("no-NO",{day:"numeric",month:"long",year:"numeric"}):"")+'</small></div><span>ARKIVERT</span></div><div class="playerArchiveStart"><b>'+(r.startedBy==="coach"?"Trener startet samtalen":"Du startet samtalen")+'</b><p>'+escapeHtml(r.message||"Ønsket generell tilbakemelding")+'</p></div>'+docs.map(d=>{const x=d.data(),date=x.createdAt?.toDate?.(),parent=x.replyToMessageId?allMessages.find(m=>m.id===x.replyToMessageId):null;return '<div class="msg '+(x.senderRole==="coach"?"coachMessage":"playerMessage")+'">'+(parent?'<div class="replyReference"><span>Svar på '+(parent.data().senderRole==="coach"?"Trener":"deg")+'</span>'+escapeHtml(parent.data().text||"")+'</div>':'')+'<div class="msgHead"><div><strong>'+(x.senderRole==="coach"?"Trener":"Deg")+'</strong>'+(date?'<small>'+date.toLocaleDateString("no-NO",{day:"numeric",month:"short",year:"numeric"})+'</small>':"")+'</div></div><p>'+escapeHtml(x.text||"")+'</p></div>'}).join("")+'</section>'}).join(""):'<p class="hint">Ingen arkiverte samtaler.</p>')+'</div></div>';archive.hidden=false;const close=()=>{archive.hidden=true;archive.innerHTML=""};$("closePlayerArchive").onclick=close;archive.querySelector(".playerArchiveOverlay").onclick=e=>{if(e.target===e.currentTarget)close()}}

function clearReplyTarget(){replyToMessageId=null;$("replyTarget").hidden=true;$("replyTargetText").textContent=""}
$("clearReplyTarget").onclick=clearReplyTarget;
$("messageToggle").onclick=()=>{showAllMessages=!showAllMessages;renderMessages()};$("archivedToggle").onclick=openPlayerArchive;
$("playerReplyBtn").onclick=async()=>{if(!activeRequestId||!account?.playerId||!currentUser||replySubmitting)return;const ta=$("playerReplyText"),text=ta.value.trim();if(!text)return;replySubmitting=true;const btn=$("playerReplyBtn");btn.disabled=true;btn.textContent="Sender…";try{await addDoc(collection(db,"developmentMessages"),{playerId:account.playerId,uid:currentUser.uid,text,senderRole:"player",createdAt:serverTimestamp(),requestId:activeRequestId,...(replyToMessageId?{replyToMessageId}: {})});ta.value="";clearReplyTarget()}catch(err){console.error("player reply",err);alert("Kunne ikke sende svaret. Prøv igjen.")}finally{replySubmitting=false;btn.disabled=false;btn.textContent="Send svar"}};
$("requestBtn").onclick=async()=>{if(!account?.playerId||requestSubmitting)return;requestSubmitting=true;const btn=$("requestBtn"),t=$("requestText").value.trim();btn.disabled=true;btn.textContent="Sender…";try{const q=query(collection(db,"developmentRequests"),where("uid","==",currentUser.uid),where("playerId","==",account.playerId));const existing=await getDocs(q);const hasOpen=existing.docs.some(d=>d.data().status==="open");if(!hasOpen){await addDoc(collection(db,"developmentRequests"),{uid:currentUser.uid,playerId:account.playerId,message:t,status:"open",createdAt:serverTimestamp(),resolvedAt:null})}$("requestText").value="";$("requestArea").hidden=true;$("activeRequest").hidden=false;$("activeRequestText").textContent=t?"Tema: "+t:"Du har bedt om en generell tilbakemelding."}catch(e){console.error(e);btn.textContent="Prøv igjen";btn.disabled=false}finally{requestSubmitting=false;if(!$("requestArea").hidden){btn.disabled=false;btn.textContent="Send forespørsel"}}};
let guardianUnsubs=[];
function stopGuardianListeners(){guardianUnsubs.forEach(f=>f?.());guardianUnsubs=[]}
function startGuardianListeners(){stopGuardianListeners();const ids=guardianAccount?.playerIds||[],state={};ids.forEach(playerId=>{state[playerId]={requests:[],messages:[]};guardianUnsubs.push(onSnapshot(query(collection(db,"developmentRequests"),where("playerId","==",playerId)),snap=>{state[playerId].requests=snap.docs.map(d=>({id:d.id,...d.data()}));renderGuardian(state)},e=>console.error("guardian requests",e)));guardianUnsubs.push(onSnapshot(query(collection(db,"developmentMessages"),where("playerId","==",playerId)),snap=>{state[playerId].messages=snap.docs.map(d=>({id:d.id,...d.data()}));renderGuardian(state)},e=>console.error("guardian messages",e)))});renderGuardian(state)}
function renderGuardian(state){const ids=guardianAccount?.playerIds||[];$("parentChildren").innerHTML=ids.length?ids.map((playerId,i)=>{const x=state[playerId]||{requests:[],messages:[]},reqs=[...x.requests].sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));return '<section class="parentChild"><div class="parentChildHead"><div><small>SPILLER '+(ids.length>1?i+1:"")+'</small><h2>Utviklingssamtaler</h2></div><span>'+reqs.length+' samtaler</span></div>'+(reqs.length?reqs.map(r=>{const ms=x.messages.filter(m=>m.requestId===r.id).sort((a,b)=>(a.createdAt?.seconds||0)-(b.createdAt?.seconds||0)),d=r.createdAt?.toDate?.();return '<details class="parentConversation" '+(r.status==="open"?"open":"")+'><summary><div><strong>'+escapeHtml(r.title||"Utviklingssamtale")+'</strong><small>'+(d?d.toLocaleDateString("no-NO",{day:"numeric",month:"long",year:"numeric"}):"")+'</small></div><span class="'+(r.status==="open"?"parentActive":"parentArchived")+'">'+(r.status==="open"?"AKTIV":"ARKIVERT")+'</span></summary><div class="parentThread"><div class="parentStart"><b>'+(r.startedBy==="coach"?"Trener startet samtalen":"Spilleren startet samtalen")+'</b><p>'+escapeHtml(r.message||"Ønsket generell tilbakemelding")+'</p></div>'+ms.map(m=>{const parent=m.replyToMessageId?x.messages.find(pm=>pm.id===m.replyToMessageId):null;return '<div class="parentMsg '+(m.senderRole==="coach"?"coach":"player")+'">'+(parent?'<div class="replyReference"><span>Svar på '+(parent.senderRole==="coach"?"Trener":"Spiller")+'</span>'+escapeHtml(parent.text||"")+'</div>':'')+'<strong>'+(m.senderRole==="coach"?"Trener":"Spiller")+'</strong><p>'+escapeHtml(m.text||"")+'</p></div>'}).join("")+'</div></details>'}).join(""):'<p class="hint">Ingen utviklingssamtaler ennå.</p>')+'</section>'}).join(""):'<div class="hero"><p>Ingen spillere er koblet til kontoen ennå.</p></div>'}

function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
onAuthStateChanged(auth,async user=>{unsubscribeRequests?.();unsubscribeRequests=null;unsubscribeMessages?.();unsubscribeMessages=null;guardianRequestUnsub?.();guardianRequestUnsub=null;stopGuardianListeners();account=null;guardianAccount=null;currentUser=user;if(guardianInviteToken){show("guardianInviteView");return}if(!user){show("authView");return}if(guardianInviteToken){try{const claim=httpsCallable(functions,"claimGuardianInvite");await claim({token:guardianInviteToken});history.replaceState({},document.title,location.pathname);location.reload();return}catch(e){console.error("claim invite",e)}}const ps=await getDoc(doc(db,"playerAccounts",user.uid));if(ps.exists()){guardianAccount=null;$("legacyActivation").hidden=true;account=ps.data();if(!account.approved||!account.playerId){$("waitingName").textContent=account.name||user.displayName||"";show("waitingView");return}$("hello").textContent=(account.name||"spiller").split(" ")[0];show("portalView");startDevelopmentListeners();startGuardianRequestListener();return}const gs=await getDoc(doc(db,"guardianAccounts",user.uid));if(gs.exists()){account=null;guardianAccount=gs.data();$("legacyActivation").hidden=true;if(!guardianAccount.approved||!(guardianAccount.playerIds||[]).length){$("parentWaitingName").textContent=guardianAccount.name||user.displayName||"";show("parentWaitingView");return}$("parentHello").textContent="Hei, "+(guardianAccount.name||"foresatt").split(" ")[0]+"!";show("parentView");startGuardianListeners();return}const legacy=await getDoc(doc(db,"users",user.uid));if(legacy.exists()&&["coach","assistantCoach"].includes(legacy.data().role)){await signOut(auth);show("authView");$("loginForm").hidden=false;$("registerForm").hidden=true;$("legacyActivation").hidden=true;msg("Denne kontoen er en trenerkonto og kan ikke aktiveres som spillerkonto.");return}account=null;guardianAccount=null;show("authView");$("loginForm").hidden=false;$("registerForm").hidden=true;$("loginTab").classList.add("active");$("registerTab").classList.remove("active");$("legacyActivation").hidden=false;$("activationName").value=user.displayName||"";msg("Du er logget inn. Aktiver Spillerportalen for å fortsette.")});