import { auth, db } from "./firebase.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.6.0/firebase-auth.js";
import { collection,getDocs,doc,getDoc,query,where,orderBy } from "https://www.gstatic.com/firebasejs/12.6.0/firebase-firestore.js";
const $=id=>document.getElementById(id);
function esc(v){const d=document.createElement("div");d.textContent=String(v??"");return d.innerHTML}
function today(){const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,"0"),String(d.getDate()).padStart(2,"0")].join("-")}
function dateObj(s){if(!s)return null;const d=new Date(s+"T12:00:00");return Number.isNaN(d.getTime())?null:d}
function shortDate(s){const d=dateObj(s);return d?d.toLocaleDateString("no-NO",{weekday:"short",day:"numeric",month:"short"}).replace(".",""):"Ikke satt"}
function fullDate(s,time){const d=dateObj(s);if(!d)return "Dato ikke satt";let x=d.toLocaleDateString("no-NO",{weekday:"long",day:"numeric",month:"long"});x=x.charAt(0).toUpperCase()+x.slice(1);return time?x+" kl "+time:x}
function badge(s){const d=dateObj(s);return d?{day:d.getDate(),month:d.toLocaleDateString("no-NO",{month:"short"}).replace(".","").toUpperCase()}:{day:"–",month:"DATO"}}
function teams(m){const ours=m.ourTeam||"Samnanger",opp=m.opponent||"Motstander";return m.venueType==="away"?{home:opp,away:ours}:{home:ours,away:opp}}
function time(m){return String(m?.time||m?.startTime||"").trim()}
function closeModal(){$("lineupModal").hidden=true;document.body.classList.remove("modalOpen")}
$("closeLineup").onclick=closeModal;$("lineupModal").onclick=e=>{if(e.target===$("lineupModal"))closeModal()};document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});
function renderGroup(type,icon,title,subtitle,players){if(!players.length)return "";return '<section class="lineupGroup '+type+'"><header><span class="groupIcon">'+icon+'</span><div><strong>'+title+'</strong><small>'+subtitle+'</small></div><b>'+players.length+'</b></header><div class="groupList">'+players.map((p,i)=>'<div class="squadPlayer"><span class="number">'+(i+1)+'</span><strong>'+esc(p.name||"")+'</strong></div>').join("")+'</div></section>'}
async function openLineup(m){try{const snap=await getDoc(doc(db,"matches",m.id));if(!snap.exists())return;const data=snap.data(),lineup=Array.isArray(data.lineup)?data.lineup:[];$("lineupTitle").textContent=m.opponent?"Mot "+m.opponent:"Lagoppstilling";$("formation").textContent=data.formation||"";$("lineupInfo").innerHTML="<strong>"+esc(fullDate(m.date,time(m)))+"</strong><span>"+esc(m.venueName||"Sted ikke satt")+"</span><span>"+(m.venueType==="away"?"Bortekamp":"Hjemmekamp")+"</span>";const pitch=$("pitch");pitch.querySelectorAll(".player").forEach(x=>x.remove());lineup.forEach(p=>{const el=document.createElement("div");el.className="player";el.style.left=Math.max(3,Math.min(97,Number(p.x)||50))+"%";el.style.top=Math.max(3,Math.min(97,Number(p.y)||50))+"%";const first=String(p.name||"").trim().split(/\s+/)[0]||"?";el.innerHTML='<span class="playerCircle">'+esc(first.charAt(0))+'</span><span class="playerName">'+esc(first)+'</span>';pitch.appendChild(el)});const saved=Object.values(data.players||{}),lineupNames=new Set(lineup.map(p=>String(p.name||"").trim().toLocaleLowerCase("no")));const starters=lineup.map(lp=>{const key=String(lp.name||"").trim().toLocaleLowerCase("no"),p=saved.find(x=>String(x.name||"").trim().toLocaleLowerCase("no")===key);return p||{name:lp.name,present:true,starter:true}});const bench=saved.filter(p=>p.present!==false&&!lineupNames.has(String(p.name||"").trim().toLocaleLowerCase("no")));const absent=saved.filter(p=>p.present===false);$("squadGroups").innerHTML=renderGroup("starter","★","STARTERE","Fra start",starters)+renderGroup("bench","↔","INNBYTTERE","Starter på benken",bench)+renderGroup("absent","○","IKKE TIL STEDE","Ikke med i kamptroppen",absent);$("lineupModal").hidden=false;document.body.classList.add("modalOpen")}catch(e){console.error(e);alert("Kunne ikke åpne lagoppstillingen.")}}
async function loadMatches(){try{const q=query(collection(db,"matches"),where("meta.date",">=",today()),orderBy("meta.date"));const snap=await getDocs(q),matches=snap.docs.map(d=>({id:d.id,...(d.data().meta||{})})).sort((a,b)=>(a.date+"T"+(time(a)||"00:00")).localeCompare(b.date+"T"+(time(b)||"00:00")));if(!matches.length){$("nextMatch").innerHTML='<div class="stateCard"><strong>Ingen kommende kamper</strong><span>Når en ny kamp registreres, vises den her.</span></div>';$("matchCount").textContent="0 kamper";return}const m=matches[0],t=teams(m);$("nextMatch").innerHTML='<button class="nextCard" type="button"><div class="nextTop"><span>NESTE KAMP</span><b class="'+(m.venueType==="away"?"away":"")+'">'+(m.venueType==="away"?"Bortekamp":"Hjemmekamp")+'</b></div><div class="fixture"><div><i>⚽</i><strong>'+esc(t.home)+'</strong></div><em>MOT</em><div><i>🛡️</i><strong>'+esc(t.away)+'</strong></div></div><div class="meta"><div><small>DATO</small><strong>'+esc(shortDate(m.date))+'</strong></div><div><small>TID</small><strong>'+esc(time(m)||"Ikke satt")+'</strong></div><div><small>STED</small><strong>'+esc(m.venueName||"Ikke satt")+'</strong></div></div><div class="openLineup"><span>Åpne lagoppstilling</span><b>→</b></div></button>';$("nextMatch").querySelector("button").onclick=()=>openLineup(m);const later=matches.slice(1);$("matchCount").textContent=later.length+" "+(later.length===1?"kamp":"kamper");$("matchGrid").innerHTML="";if(!later.length){$("matchGrid").innerHTML='<div class="stateCard small">Ingen flere kamper er registrert.</div>';return}later.forEach(m=>{const d=badge(m.date),t=teams(m),b=document.createElement("button");b.className="matchCard";b.type="button";b.innerHTML='<span class="dateBadge"><strong>'+d.day+'</strong><small>'+esc(d.month)+'</small></span><span class="matchMain"><small>'+(m.venueType==="away"?"Bortekamp":"Hjemmekamp")+'</small><strong>'+esc(t.home)+" – "+esc(t.away)+'</strong><span>'+esc(m.venueName||"Sted ikke satt")+'</span></span><span class="right"><strong>'+esc(time(m)||"–")+'</strong><span>›</span></span>';b.onclick=()=>openLineup(m);$("matchGrid").appendChild(b)})}catch(e){console.error(e);$("nextMatch").innerHTML='<div class="stateCard">Kunne ikke laste kampene.</div>'}}
onAuthStateChanged(auth,async user=>{if(!user){location.replace("index.html");return}try{const a=await getDoc(doc(db,"playerAccounts",user.uid));if(!a.exists()||!a.data().approved||!a.data().playerId){location.replace("index.html");return}await loadMatches()}catch(e){console.error(e);location.replace("index.html")}});
